### PR TITLE
Fix commissions paypal field

### LINKED ISSUE #160: Missing Span ID + Legend Wrap
The "PayPal Email Address" heading is missing a Span ID and Legend wrap, meaning the heading can't be targeted for styling to match the other form elements on the EDD Account page.

### PR DESCRIPTION
**Pull request by ghost1227**
Fixes #160

### CODE REVIEW

File: includes/short-codes.php [hunk 1]
```diff
@@ -624,14 +624,18 @@ function eddc_profile_editor_paypal() {
...
+
+		<p id="edd_profile_paypal_wrap">
+			<label for="eddc-paypal-email"><?php _e( 'PayPal Email Address', 'eddc' ); ?></label>
+			<input name="eddc_paypal_email" id="eddc-paypal-email" class="text edd-input" type="email" value="<?php echo esc_attr( $email ); ?>" />
+		</p>
+	</fieldset>
 	<?php
 }
-add_action( 'edd_profile_editor_after_password', 'eddc_profile_editor_paypal', 9999 );
+add_action( 'edd_profile_editor_after_address_fields', 'eddc_profile_editor_paypal', 9999 );
```
Comment (pippinsplugins) [inline includes/short-codes.php]: Let's add an EDD version compare here and only use the new hook when the site is running the proper version.

File: includes/short-codes.php [hunk 2]
```diff
@@ -623,15 +623,34 @@ function eddc_profile_editor_paypal() {
...
+		<p>
+			<strong><?php _e( 'Commissions', 'eddc' ); ?></strong><br />
+			<label for="eddc-paypal-email"><?php _e( 'PayPal Email Address', 'eddc' ); ?></label>
+			<input name="eddc_paypal_email" id="eddc-paypal-email" class="text edd-input" type="email" value="<?php echo esc_attr( $email ); ?>" />
+		</p>	
+		<?php
+	}
 }
-add_action( 'edd_profile_editor_after_password', 'eddc_profile_editor_paypal', 9999 );
+if ( version_compare( EDD_VERSION, '2.7.8', '>=' ) ) {
```
Comment (pippinsplugins) [inline includes/short-codes.php]: Let's add `defined( 'EDD_VERSION' )` here just to be extra safe.

Comment (ghost1227) [inline includes/short-codes.php]: Done!
